import io
from fpdf import FPDF
from datetime import datetime

# Project Palette
# Primary: #5A8252 (90, 130, 82)
# Light BG: #EFF7D3 (239, 247, 211)

class DiagnosisReportPDF(FPDF):
    def __init__(self, record, interpretation_map, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.record = record
        self.interpretation_map = interpretation_map
        
    def header(self):
        # Header Box
        self.set_fill_color(90, 130, 82)
        self.rect(0, 0, 210, 30, 'F')
        
        # Title
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, 'AI Plant Stress Detection System', border=0, new_x='LMARGIN', new_y='NEXT', align='C')
        
        self.set_font('Helvetica', '', 12)
        self.cell(0, 10, 'Diagnosis Report (MVP)', border=0, new_x='LMARGIN', new_y='NEXT', align='C')
        self.ln(10)
        
        # Demo Watermark
        if self.record.is_demo:
            self.set_font('Helvetica', 'B', 40)
            self.set_text_color(255, 200, 200) # Faint red
            # Rotate not strictly needed, just place it in background or top right
            
    def footer(self):
        self.set_y(-25)
        
        # Scientific Limitation Box
        self.set_fill_color(240, 240, 240)
        self.set_font('Helvetica', 'B', 8)
        self.set_text_color(200, 50, 50)
        self.cell(0, 5, "SCIENTIFIC LIMITATION NOTICE:", new_x='LMARGIN', new_y='NEXT')
        self.set_font('Helvetica', '', 8)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 4, "Model confidence indicates statistical classification probability. It does NOT represent biological severity. This report is generated by an automated edge-AI model and should be verified with ground-truth agronomic testing where required.", fill=True)
        
        # Page number
        self.set_text_color(128, 128, 128)
        self.cell(0, 5, f'Page {self.page_no()}', align='C')

    def generate(self):
        self.add_page()
        
        # If Demo, add a visible badge at the top
        if self.record.is_demo:
            self.set_font('Helvetica', 'B', 14)
            self.set_text_color(220, 50, 50)
            self.cell(0, 10, "*** DEMONSTRATION DATA ***", align='C', new_x='LMARGIN', new_y='NEXT')
            self.ln(5)
            
        self.set_text_color(0, 0, 0)
        
        # 1. Metadata Section
        self.set_font('Helvetica', 'B', 12)
        self.set_fill_color(239, 247, 211) # Light BG
        self.cell(0, 8, " 1. Measurement Details", fill=True, new_x='LMARGIN', new_y='NEXT')
        
        self.set_font('Helvetica', '', 10)
        self.ln(2)
        
        dt_str = self.record.measurement_timestamp.strftime("%Y-%m-%d %H:%M:%S UTC")
        
        def dict_row(k, v):
            self.set_font('Helvetica', 'B', 10)
            self.cell(40, 6, k, border=0)
            self.set_font('Helvetica', '', 10)
            self.cell(0, 6, str(v), border=0, new_x='LMARGIN', new_y='NEXT')
            
        dict_row("Report ID:", self.record.measurement_id)
        dict_row("Date & Time:", dt_str)
        dict_row("Plant Species:", self.record.plant_species.capitalize())
        dict_row("Plant ID:", self.record.plant_id)
        dict_row("Sensor Profile:", self.record.sensor_profile)
        dict_row("Model Instance:", self.record.model_id)
        
        self.ln(5)
        
        # 2. Diagnosis Results
        self.set_font('Helvetica', 'B', 12)
        self.cell(0, 8, " 2. AI Diagnosis", fill=True, new_x='LMARGIN', new_y='NEXT')
        self.ln(2)
        
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(90, 130, 82)
        self.cell(0, 10, f"{self.record.diagnosis}", new_x='LMARGIN', new_y='NEXT')
        
        self.set_text_color(0, 0, 0)
        conf_str = f"{(self.record.model_confidence * 100):.1f}%"
        
        dict_row("Model Confidence:", conf_str)
        dict_row("Biological Severity:", "Not supported in current MVP")
        
        self.ln(5)
        
        # 3. Interpretation & Recommendation
        mapping = {"interpretation": "N/A", "recommendation": "N/A"}
        for k, v in self.interpretation_map.items():
            if v["diagnosis"] == self.record.diagnosis:
                mapping = v
                break
                
        self.set_font('Helvetica', 'B', 12)
        self.cell(0, 8, " 3. Interpretation & Recommendation", fill=True, new_x='LMARGIN', new_y='NEXT')
        self.ln(2)
        
        self.set_font('Helvetica', 'B', 10)
        self.cell(0, 6, "Interpretation:", new_x='LMARGIN', new_y='NEXT')
        self.set_font('Helvetica', '', 10)
        self.multi_cell(0, 6, mapping.get("interpretation", "Plant-specific recommendation layer pending validated knowledge configuration."))
        
        self.ln(2)
        self.set_font('Helvetica', 'B', 10)
        self.cell(0, 6, "Recommendation:", new_x='LMARGIN', new_y='NEXT')
        self.set_font('Helvetica', '', 10)
        self.multi_cell(0, 6, mapping.get("recommendation", "Plant-specific recommendation layer pending validated knowledge configuration."))
        
        # Output to bytes
        pdf_bytes = self.output()
        return bytes(pdf_bytes)
