import io
from fpdf import FPDF
from datetime import datetime

# Project Palette
# Primary: #5A8252 (90, 130, 82)
# Light BG: #EFF7D3 (239, 247, 211)

class DiagnosisReportPDF(FPDF):
    def __init__(self, record, interpretation_map, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.record = record
        self.interpretation_map = interpretation_map
        
    def header(self):
        # Header Box
        self.set_fill_color(90, 130, 82)
        self.rect(0, 0, 210, 30, 'F')
        
        # Title
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, 'AI Plant Stress Detection System', border=0, new_x='LMARGIN', new_y='NEXT', align='C')
        
        self.set_font('Helvetica', '', 12)
        self.cell(0, 10, 'Diagnosis Report (MVP)', border=0, new_x='LMARGIN', new_y='NEXT', align='C')
        self.ln(10)
            
    def footer(self):
        self.set_y(-25)
        
        # Scientific Limitation Box
        self.set_fill_color(240, 240, 240)
        self.set_font('Helvetica', 'B', 8)
        self.set_text_color(200, 50, 50)
        self.cell(0, 5, "SCIENTIFIC LIMITATION NOTICE:", new_x='LMARGIN', new_y='NEXT')
        self.set_font('Helvetica', '', 8)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 4, "Model confidence indicates statistical classification probability. It does NOT represent biological severity. This report is generated by an automated edge-AI model and should be verified with ground-truth agronomic testing where required.", fill=True)
        
        # Page number
        self.set_text_color(128, 128, 128)
        self.cell(0, 5, f'Page {self.page_no()}', align='C')

    def generate(self):
        self.add_page()
            
        self.set_text_color(0, 0, 0)
        
        # 1. Metadata Section
        self.set_font('Helvetica', 'B', 12)
        self.set_fill_color(239, 247, 211) # Light BG
        self.cell(0, 8, " 1. Measurement Details", fill=True, new_x='LMARGIN', new_y='NEXT')
        
        self.set_font('Helvetica', '', 10)        # Header
        self.set_font('Helvetica', 'B', 20)
        self.set_text_color(90, 130, 82)
        self.cell(0, 15, 'Plant Stress Diagnostic Report', align='C', new_x='LMARGIN', new_y='NEXT')
        self.ln(5)
        
        # 1. Measurement Information
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(90, 130, 82)
        self.cell(0, 10, '1. Measurement Information', new_x='LMARGIN', new_y='NEXT')
        self.set_font('Helvetica', '', 11)
        self.set_text_color(0, 0, 0)
        
        info = [
            f"Plant Species: {self.record.plant_species.capitalize()}",
            f"Biological Plant ID: {self.record.plant_id}",
            f"Experimental Day: {self.record.experimental_day or 'Unknown'}",
            f"Sample ID: {self.record.sample_id or 'Unknown'}",
            f"Dataset Source: {self.record.dataset_source}",
            f"Sensor Profile: {self.record.sensor_profile}",
            f"Date / Time: {self.record.measurement_timestamp.strftime('%Y-%m-%d %H:%M:%S')}",
            f"Model Version: {self.record.model_id}"
        ]
        for line in info:
            self.cell(0, 6, line, new_x='LMARGIN', new_y='NEXT')
            
        self.ln(5)
        
        # 2. AI Diagnosis
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(90, 130, 82)
        self.cell(0, 10, '2. AI Diagnosis', new_x='LMARGIN', new_y='NEXT')
        self.set_text_color(0, 0, 0)
        
        self.set_font('Helvetica', 'B', 12)
        self.cell(45, 8, 'Predicted Condition:')
        self.set_font('Helvetica', '', 12)
        self.cell(0, 8, self.record.diagnosis, new_x='LMARGIN', new_y='NEXT')
        
        self.set_font('Helvetica', 'B', 12)
        self.cell(45, 8, 'Model Confidence:')
        self.set_font('Helvetica', '', 12)
        self.cell(0, 8, f"{(self.record.model_confidence * 100):.1f}%", new_x='LMARGIN', new_y='NEXT')
        
        # Severity
        self.set_font('Helvetica', 'I', 10)
        self.multi_cell(0, 6, "Note: Model confidence is statistical probability. Biological severity estimation is not validated because the training dataset does not contain severity labels.")
        self.ln(3)

        # 3. Class Probabilities
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(90, 130, 82)
        self.cell(0, 10, '3. Class Probabilities', new_x='LMARGIN', new_y='NEXT')
        self.set_text_color(0, 0, 0)
        self.set_font('Helvetica', '', 11)
        
        import json
        probs = {}
        try:
            if getattr(self.record, 'class_probabilities_json', None):
                probs = json.loads(self.record.class_probabilities_json)
        except: pass

        if probs:
            for cls, p in probs.items():
                self.cell(0, 6, f"{cls}: {(p*100):.1f}%", new_x='LMARGIN', new_y='NEXT')
        else:
            self.cell(0, 6, "Not available.", new_x='LMARGIN', new_y='NEXT')
        
        # Mapping logic
        mapping = {"interpretation": "", "recommendation": "", "potential_effects": []}
        for key, val in self.interpretation_map.items():
            if val["diagnosis"] == self.record.diagnosis:
                mapping = val
                break
                
        self.ln(5)
        
        # 4. Model Explainability
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(90, 130, 82)
        self.cell(0, 10, '4. Model Explainability', new_x='LMARGIN', new_y='NEXT')
        self.set_text_color(0, 0, 0)
        
        top_features = []
        try:
            if self.record.top_features_json:
                top_features = json.loads(self.record.top_features_json)
        except: pass
        
        if top_features:
            self.set_font('Helvetica', 'B', 11)
            self.cell(0, 6, f"Top model-relevant features: {', '.join(top_features)}", new_x='LMARGIN', new_y='NEXT')
        
        self.set_font('Helvetica', 'I', 10)
        self.multi_cell(0, 5, "These features are among the most influential in the trained Random Forest model. They provide model-level evidence for how the classifier uses the extracted spectral information.")
        self.ln(2)
        
        self.set_font('Helvetica', '', 11)
        self.multi_cell(0, 6, f"Biological Interpretation: {mapping.get('interpretation', 'N/A')}")
        self.ln(5)

        # 5. Potential Effects
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(90, 130, 82)
        self.cell(0, 10, '5. Potential Effects', new_x='LMARGIN', new_y='NEXT')
        self.set_text_color(0, 0, 0)
        self.set_font('Helvetica', 'I', 10)
        self.multi_cell(0, 5, "These are potential effects associated with the detected stress condition and are not direct measurements from the current spectrum.")
        self.set_font('Helvetica', '', 11)
        effects = mapping.get('potential_effects', [])
        for eff in effects:
            self.cell(0, 6, f"- {eff}", new_x='LMARGIN', new_y='NEXT')
        self.ln(5)

        # 6. Recommendation
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(90, 130, 82)
        self.cell(0, 10, '6. Plant-Specific Recommendation', new_x='LMARGIN', new_y='NEXT')
        self.set_text_color(0, 0, 0)
        self.set_font('Helvetica', '', 11)
        self.multi_cell(0, 6, mapping.get('recommendation', 'N/A'))
        
        # 6. Spectral Features Table
        features = {}
        try:
            if self.record.features_json:
                features = json.loads(self.record.features_json)
        except: pass
        
        if features:
            self.ln(10)
            self.add_page()
            self.set_font('Helvetica', 'B', 14)
            self.set_text_color(90, 130, 82)
            self.cell(0, 10, '6. Spectral Feature Analysis (Extracted)', new_x='LMARGIN', new_y='NEXT')
            self.set_text_color(0, 0, 0)
            
            self.set_fill_color(239, 247, 211)
            self.set_font('Helvetica', 'B', 10)
            self.cell(80, 8, 'Feature', border=1, fill=True)
            self.cell(80, 8, 'Value', border=1, fill=True, new_x='LMARGIN', new_y='NEXT')
            
            self.set_font('Helvetica', '', 10)
            for feat, val in features.items():
                self.cell(80, 8, str(feat), border=1)
                self.cell(80, 8, f"{val:.4f}", border=1, new_x='LMARGIN', new_y='NEXT')
        
        # Output to bytes
        pdf_bytes = self.output()
        return bytes(pdf_bytes)
